swagger: '2.0'

info:
  title: Foo API
  description: An API demo
basePath: /api

consumes:
  - application/json
produces:
  - application/json

definitions:

  Foo:
    allOf:
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
      - $ref: "#/definitions/NewFoo"

  NewFoo:
    type: object
    required:
      - bar
    properties:
      bar:
        type: string
        format: date-time
      baz:
        type: string
        description: Create a business case from a template

paths:

  /foos:

    get:
      operationId: GetFooList
      responses:
        200:
          description: Foo List
          schema:
            type: array
            items:
              $ref: "#/definitions/Foo"
    post:
      operationId: CreateFoo
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/NewFoo"
      responses:
        201:
          description: Foo created

    put:
      operationId: ModifyFoo
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Foo"
      responses:
        204:
          description: Foo modified

  /foos/{id}:

    get:
      operationId: GetFoo
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        204:
          description: Foo removed

    delete:
      operationId: DeleteFoo
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        204:
          description: Foo removed